# Trial Name: final4_kitting.yaml
# ARIAC2023
# 2023-06-20 09:28:42

# ENVIRONMENT SETUP
time_limit: 600 # options: -1 (no time limit) or number of seconds
gazebo_state_logging: true

kitting_trays: # Which kitting trays will be spawned
  tray_ids: [4,5]
  slots: [1,4]

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2:
      - type: 'sensor'
        color: 'red'
        slots: [1,9]
    bin6:
      - type: 'regulator'
        color: 'purple'
        slots: [1,3,9]
    bin5:
      - type: 'battery'
        color: 'red'
        slots: [1]


# ORDER SETUP
orders:
  - id: 'FINAL4KITTING1'
    type: 'kitting'
    announcement:
      time_condition: 0.0
    priority: false
    kitting_task:
      agv_number: 1
      tray_id: 4
      destination: 'warehouse'
      products:
        - type: 'sensor'
          color: 'red'
          quadrant: 1
        - type: 'regulator'
          color: 'purple'
          quadrant: 2
        - type: 'regulator'
          color: 'purple'
          quadrant: 3
  - id: 'FINAL4KITTING2'
    type: 'kitting'
    announcement:
      part_place_condition:
        agv: 1
        type: 'regulator'
        color: 'purple'  
    priority: true
    kitting_task:
      agv_number: 3
      tray_id: 5
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'red'
          quadrant: 3
        - type: 'battery'
          color: 'red'
          quadrant: 4
