# Trial Name: final5_kitting.yaml
# ARIAC2023
# 2023-06-20 09:34:08

# ENVIRONMENT SETUP
time_limit: 800 # options: -1 (no time limit) or number of seconds
gazebo_state_logging: true

kitting_trays: # Which kitting trays will be spawned
  tray_ids: [0,9,0,9]
  slots: [4,6,1,2]

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'sensor'
        color: 'orange'
        slots: [1,3,7,9]
    bin2:
      - type: 'sensor'
        color: 'purple'
        slots: [1,3,7,9]
    bin5:
      - type: 'sensor'
        color: 'purple'
        slots: [4]
      - type: 'sensor'
        color: 'orange'
        slots: [6]
# ORDER SETUP
orders:
  - id: 'FINAL5KITTING1'
    type: 'kitting'
    announcement:
      time_condition: 0.0
    priority: false
    kitting_task:
      agv_number: 2
      tray_id: 0
      destination: 'warehouse'
      products:
        - type: 'sensor'
          color: 'orange'
          quadrant: 1
        - type: 'sensor'
          color: 'orange'
          quadrant: 2
        - type: 'sensor'
          color: 'orange'
          quadrant: 3
        - type: 'sensor'
          color: 'orange'
          quadrant: 4
  - id: 'FINAL5KITTING2'
    type: 'kitting'
    announcement:
      time_condition: 30.0
    priority: true
    kitting_task:
      agv_number: 4
      tray_id: 9
      destination: 'warehouse'
      products:
        - type: 'sensor'
          color: 'purple'
          quadrant: 1
        - type: 'sensor'
          color: 'purple'
          quadrant: 2
        - type: 'sensor'
          color: 'purple'
          quadrant: 3
        - type: 'sensor'
          color: 'purple'
          quadrant: 4

# GLOBAL CHALLENGES
challenges:
- robot_malfunction:
    duration: 15.0
    robots_to_disable: ['floor_robot']
    time_condition: 0.0
- faulty_part:
    order_id: 'FINAL5KITTING1'
    quadrant1: true
- faulty_part:
    order_id: 'FINAL5KITTING2'
    quadrant4: true