# Trial Name: final1_kitting.yaml
# ARIAC2023
# 2023-06-20 09:03:07

# ENVIRONMENT SETUP
time_limit: 600 # options: -1 (no time limit) or number of seconds
gazebo_state_logging: true

kitting_trays: # Which kitting trays will be spawned
  tray_ids: [0,1]
  slots: [1,2]

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin6:
      - type: 'regulator'
        color: 'red'
        slots: [1,3,7,9]
    bin5:
      - type: 'battery'
        color: 'purple'
        slots: [1,3,7,9]


# ORDER SETUP
orders:
  - id: 'FINAL1KITTING1'
    type: 'kitting'
    announcement:
      time_condition: 0.0
    priority: false
    kitting_task:
      agv_number: 2
      tray_id: 0
      destination: 'warehouse'
      products:
        - type: 'regulator'
          color: 'red'
          quadrant: 1
        - type: 'regulator'
          color: 'red'
          quadrant: 3
  - id: 'FINAL1KITTING2'
    type: 'kitting'
    announcement:
      time_condition: 0.0
    priority: false
    kitting_task:
      agv_number: 3
      tray_id: 1
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'purple'
          quadrant: 1
        - type: 'battery'
          color: 'purple'
          quadrant: 2

# GLOBAL CHALLENGES
challenges:
  - faulty_part:
      order_id: 'FINAL1KITTING1'
      quadrant3: true
  - sensor_blackout:
      duration: 30.0
      sensors_to_disable: ['break_beam', 'proximity', 'laser_profiler', 'lidar', 'camera', 'logical_camera']
      part_place_condition:
        type: 'regulator'
        color: 'red'
        agv: 2
