# Trial Name: final6_kitting.yaml
# ARIAC2023
# Challenges:
#   high-priority order
#   faulty part
#   flipped parts (regulator)

# ENVIRONMENT SETUP
time_limit: 800 # options: -1 (no time limit) or number of seconds
gazebo_state_logging: true

kitting_trays: # Which kitting trays will be spawned
  tray_ids: [1,2,3]
  slots: [1,3,5]

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'pump'
        color: 'orange'
        slots: [1,3]
    bin2:
      - type: 'regulator'
        color: 'red'
        slots: [1,3]
        flipped: true
    bin3:
      - type: 'battery'
        color: 'purple'
        slots: [1,3]
    bin6:
      - type: 'pump'
        color: 'orange'
        slots: [1]
      - type: 'regulator'
        color: 'red'
        slots: [3]
      - type: 'battery'
        color: 'purple'
        slots: [5]

# ORDER SETUP
orders:
  - id: 'FINAL6KITTING1'
    type: 'kitting'
    announcement:
      time_condition: 0.0
    priority: false
    kitting_task:
      agv_number: 1
      tray_id: 1
      destination: 'warehouse'
      products:
        - type: 'pump'
          color: 'orange'
          quadrant: 1
        - type: 'pump'
          color: 'orange'
          quadrant: 3
  - id: 'FINAL6KITTING2'
    type: 'kitting'
    announcement:
      time_condition: 10.0
    priority: false
    kitting_task:
      agv_number: 2
      tray_id: 2
      destination: 'warehouse'
      products:
        - type: 'regulator'
          color: 'red'
          quadrant: 1
        - type: 'regulator'
          color: 'red'
          quadrant: 3
  - id: 'FINAL6KITTING3'
    type: 'kitting'
    announcement:
      time_condition: 20.0
    priority: true
    kitting_task:
      agv_number: 3
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'purple'
          quadrant: 1
        - type: 'battery'
          color: 'purple'
          quadrant: 3

# GLOBAL CHALLENGES
challenges:
  - faulty_part:
      order_id: 'FINAL6KITTING1'
      quadrant1: true
  - faulty_part:
      order_id: 'FINAL6KITTING2'
      quadrant1: true
  - faulty_part:
      order_id: 'FINAL6KITTING3'
      quadrant1: true