# Trial Name: final10_assembly.yaml
# ARIAC2023
# 2023-06-20 09:49:26

# ENVIRONMENT SETUP
time_limit: 600 # options: -1 (no time limit) or number of seconds
gazebo_state_logging: true

# kitting_trays: # Which kitting trays will be spawned
#   tray_ids: [0]
#   slots: [1]

parts:
  agvs:
    agv2:
      tray_id: 0
      parts:
      - type: 'pump'
        color: 'purple'
        quadrant: 1
      - type: 'battery'
        color: 'purple'
        quadrant: 2
      - type: 'sensor'
        color: 'purple'
        quadrant: 3
      - type: 'regulator'
        color: 'purple'
        quadrant: 4



# ORDER SETUP
orders:
  - id: 'FINAL10ASSEMBLY'
    type: 'assembly'
    announcement:
      time_condition: 0.0
    priority: false
    assembly_task:
      agv_number: [2]
      station: 'as2'
      products:
        - type: 'pump'
          color: 'purple'
          assembled_pose: # relative to briefcase frame
            xyz: [0.14, 0.0, 0.02]
            rpy: [0, 0, '-pi/2']
          assembly_direction: [0, 0, -1]
        - type: 'battery'
          color: 'purple'
          assembled_pose: # relative to briefcase frame
            xyz: [-0.15, 0.035, 0.043]
            rpy: [0, 0, 'pi/2']
          assembly_direction: [0, 1, 0]
        - type: 'sensor'
          color: 'purple'
          assembled_pose: # relative to briefcase frame
            xyz: [-0.1, 0.395, 0.045]
            rpy: [0, 0, '-pi/2']
          assembly_direction: [0, -1, 0]
        - type: 'regulator'
          color: 'purple'
          assembled_pose: # relative to briefcase frame
            xyz: [0.175, -0.223, 0.215]
            rpy: ['pi/2', 0, '-pi/2']
          assembly_direction: [0, 0, -1]

challenges:
  - sensor_blackout:
      duration: 300.0
      sensors_to_disable: ['break_beam', 'proximity', 'laser_profiler', 'lidar', 'camera', 'logical_camera']
      time_condition: 40
  - human:
      behavior: 'indifferent'
      time: 5.0